INSERT INTO Staff (FirstName, LastName, Department, Role) VALUES
('Carlos', 'Reyes', 'Cardiology', 'Doctor'),
('Maria', 'Santos', 'Dermatology', 'Doctor'),
('Antonio', 'Cruz', 'Gastroenterology', 'Doctor'),
('Isabel', 'Garcia', 'Neurology', 'Doctor'),
('Ramon', 'Dela Cruz', 'Oncology', 'Doctor'),
('Elena', 'Bautista', 'Ophthalmology', 'Doctor'),
('Jorge', 'Fernandez', 'Orthopedics', 'Doctor'),
('Patricia', 'Lopez', 'Pediatrics', 'Doctor'),
('Miguel', 'Torres', 'Psychiatry', 'Doctor'),
('Sofia', 'Villanueva', 'Pulmonology', 'Doctor'),
('Andrea', 'Mendoza', 'Emergency Department', 'Nurse'),
('Liza', 'Gutierrez', 'Pediatric Department', 'Nurse'),
('Catherine', 'Jimenez', 'Medical-Surgical Department', 'Nurse'),
('Erika', 'Castillo', 'Oncology Department', 'Nurse'),
('Grace', 'Ramos', 'Labor and Delivery', 'Nurse'),
('Monica', 'Aguilar', 'Emergency Department', 'Nurse'),
('Juliana', 'Perez', 'Pediatric Department', 'Nurse'),
('Karen', 'Santiago', 'Medical-Surgical Department', 'Nurse'),
('Melissa', 'Morales', 'Oncology Department', 'Nurse'),
('Regina', 'Navarro', 'Labor and Delivery', 'Nurse');