CREATE TABLE [dbo].[Staff]
(
	[StaffID] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DepartmentID INT NOT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	Role VARCHAR(50) NOT NULL,
	Phone VARCHAR(15) NULL,
	Email VARCHAR(100) NULL,
	HireDate DATETIME NOT NULL DEFAULT GETDATE()
	FOREIGN KEY (DepartmentID) REFERENCES Departments(DepartmentID)
)
